name: PetStore

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 0: Checkout do código
      - name: Checkout
        uses: actions/checkout@v3

      # Step 1: Verifica versões
      - name: Check version Newman and Node
        run: |
          newman --version
          node --version
          
      # Step 2: Instala o reporter HTML extra
      - name: Install Newman-Reporter-Htmlextra
        run: sudo npm install -g newman-reporter-htmlextra
        
      # Step 3: Executa a coleção do Postman
      - name: Execute Postman Collection
        run: |
          newman run postman/collections/46757820-32ab63d3-1e2a-4c3f-bf47-52616cde4ee7.json \
            -e ./Petstore.Homologação.json \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export ./results/Report.html
   
      # Step 4: Faz upload do relatório gerado
      - name: Archive HTML report
        uses: actions/upload-artifact@v4
        with:
          name: Relatorio-Newman
          path: ./results/Report.html
